judovana/java-runtime-decompiler

- runtime-decompiler/src/main/java/org/jrd/backend/data/Main.java
- runtime-decompiler/src/main/java/org/jrd/frontend/VmDecompilerInformationController.java
More switches will require more logic to handel, this wil lbe done on the fly.
> Added initial CLI switch to list classes. For now, no serious switch handling

- runtime-decompiler/src/main/java/org/jrd/backend/data/Main.java
- runtime-decompiler/src/main/java/org/jrd/frontend/VmDecompilerInformationController.java
- some advice how to proceed with remote VMs would be nice :)
> Implemented CLI loading of classlist from local VM

- start.sh
Repaired start.sh to work with mvn clean install
> Repaired start.sh

- decompiler_agent/src/main/java/org/jrd/agent/AgentActionWorker.java
- decompiler_agent/src/main/java/org/jrd/agent/InstrumentationProvider.java
- decompiler_agent/src/main/java/org/jrd/agent/Transformer.java
- runtime-decompiler/src/main/java/org/jrd/backend/communication/Communicate.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/AgentRequestAction.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/DecompilerRequestReceiver.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Cli.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/BytecodeDecompilerView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/FiletoClassValidator.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/RewriteClassDialog.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/VmDecompilerInformationController.java
> Class override

- runtime-decompiler/src/main/java/org/jrd/backend/data/Config.java
Changed the way the configuration is stored according to #8 to use JSON.
> Improved the confing file to use JSON

- LICENSE
- README.md
- runtime-decompiler/src/main/java/org/jrd/backend/data/Directories.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/DecompilerWrapperInformation.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/ExpandableUrl.java
- runtime-decompiler/src/main/java/org/jrd/frontend/ConfigureFrame/ConfigureView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/LicenseFrame/LicenseView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/BytecodeDecompilerView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/MainFrameView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/VmDecompilerInformationController.java
- runtime-decompiler/src/main/java/org/jrd/frontend/PluginMangerFrame/PluginConfigurationEditorView.java
- start.bat
This PR is the small tweaks part of #53. As stated there, these commits address issues:
7cfa751 - #9 & #29 
92db5cb  - #28 (at least the the first option of Radek's answer)
543b690  - #35
> General improvements

- images/image.sh
- runtime-decompiler/src/main/java/org/jrd/backend/data/Directories.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/ExpandableUrl.java
- runtime-decompiler/src/main/java/org/jrd/frontend/ConfigureFrame/ConfigureView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/MainFrameView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/VmDecompilerInformationController.java
- runtime-decompiler/src/main/java/org/jrd/frontend/PluginMangerFrame/FileSelectorArrayRow.java
- runtime-decompiler/src/test/java/org/jrd/backend/decompiling/ExpandableUrlTest.java
- runtime-decompiler/src/test/java/org/jrd/frontend/PluginMangerFrame/FileSelectorArrayRowTest.java
- start.bat
- start.sh
Changes to .sh and .bat scripts, introduction of new macro and runtime system property.
> Scripts and macros

- images/image.sh
> Pre-release touch-ups 2

- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/LoadingDialog.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/MainFrameView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/RewriteClassDialog.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/ScreenFinder.java
fixing https://github.com/pmikova/java-runtime-decompiler/issues/60
> fixed issue where dialogues were appearing on wrong screen

- decompiler_agent/src/main/java/org/jrd/agent/InstrumentationProvider.java
- runtime-decompiler/src/main/java/org/jrd/backend/communication/InstallDecompilerAgentImpl.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/AgentRequestAction.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/DecompilerWrapperInformation.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/PluginManager.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/BytecodeDecompilerView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/MainFrameView.java
https://github.com/pmikova/java-runtime-decompiler/issues/39
> #39 fixed doclint issues

- runtime-decompiler/src/main/java/org/fife/ui/hex/event/HexSearchActionListener.java
- runtime-decompiler/src/main/java/org/fife/ui/hex/event/HexSearchDocumentListener.java
- runtime-decompiler/src/main/java/org/fife/ui/hex/package-info.java
- runtime-decompiler/src/main/java/org/fife/ui/hex/swing/HexSearch.java
- runtime-decompiler/src/main/java/org/fife/ui/hex/swing/HexSearchParseException.java
- runtime-decompiler/src/main/java/org/fife/ui/hex/swing/SearchState.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/BytecodeDecompilerView.java
Search in hex view has been implemented.
Typo has been fixed.
> Hex search implemented

- runtime-decompiler/src/test/java/org/jrd/frontend/HexSearch/HexSearchTest.java
Added some basic HexSearch tests testing basic functionality and edge cases.
> HexSearch tests added

- start.sh
Recent merge that updated one dependency broke the start.sh. This fixes it.
Fixes #74
> Fixed start.sh so it searches for CPS and not JC

- runtime-decompiler/src/main/java/org/jrd/backend/communication/FsAgent.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/ArchiveManager.java
Support for nested jars (and zips, needs edit) in FsAgent.
Currently supports:
- Listing of classes
- Reading of classes
TODO:
- Editing/Rewriting of classes
> Nested jars support

- runtime-decompiler/src/main/java/org/jrd/backend/data/Cli.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/RewriteClassDialog.java
The class name `Compiler` is going away.
> Use specific compiler name

- README.md
- runtime-decompiler/src/main/java/org/jrd/backend/core/DecompilerRequestReceiver.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Config.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/ExpandableUrl.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/BytecodeDecompilerView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/MainFrame/VmDecompilerInformationController.java
> Minor fixes

- runtime-decompiler/src/plugins/JasmDecompilerWrapper.json
Presumably originated in d8b5a037.
> Fixed default JASM jar path

- runtime-decompiler/src/main/java/org/jrd/backend/data/ArchiveManager.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/ArchiveManagerOptions.java
ArchiveManagerOption is added which will be used to edit functioning of ArchiveManager.
Currently it is ready to be used with shouldOpen, as it provides a way of adding custom extensions that should be opened.
> Custom extension that should be opened.

- runtime-decompiler/src/main/java/org/jrd/backend/communication/FsAgent.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/ArchiveManager.java
...which prevented overwriting FS VMs on Windows.
> Fixed stale handles being open

- .plugin_config/codestyle.xml
- decompiler_agent/src/main/java/org/jrd/agent/AgentActionWorker.java
- runtime-decompiler/src/main/java/org/fife/ui/hex/swing/HexEditor.java
- runtime-decompiler/src/main/java/org/jrd/backend/communication/Communicate.java
- runtime-decompiler/src/main/java/org/jrd/backend/communication/ErrorCandidate.java
- runtime-decompiler/src/main/java/org/jrd/backend/communication/FsAgent.java
- runtime-decompiler/src/main/java/org/jrd/backend/communication/TopLevelErrorCandidate.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/AgentRequestAction.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/DecompilerRequestReceiver.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/Logger.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Cli.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Help.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Main.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/PluginManager.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/BytecodeDecompilerView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/DecompilationController.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/GlobalConsole.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/MainFrameView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/overwrite/OverwriteClassDialog.java
- runtime-decompiler/src/main/java/org/jrd/frontend/utility/CommonUtils.java
- runtime-decompiler/src/main/java/org/jrd/frontend/utility/TeeOutputStream.java
issue: the button bar in code view nw do not fit
> Implemented INIT_CLASS, implemented pernament conosle, implemened verbose errors

- runtime-decompiler/src/main/java/org/jrd/backend/communication/RuntimeCompilerConnector.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Cli.java
Would fixe https://github.com/pmikova/java-runtime-decompiler/issues/135 and https://github.com/pmikova/java-runtime-decompiler/issues/134 if CLPC is doing its work properly (verified)
> Lazy class init in compilation

- runtime-decompiler/src/main/java/org/jrd/backend/data/ArchiveManager.java
Each read now leads to unpack, and each write leads to pack
> nested jars no longer have cache

- runtime-decompiler/src/main/java/org/jrd/backend/data/Config.java
- runtime-decompiler/src/main/java/org/jrd/backend/data/Main.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/BytecodeDecompilerView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/DecompilationController.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/GlobalConsole.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/LoadingDialog.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/MainFrameView.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/main/OverridesManager.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/overwrite/OverwriteClassDialog.java
- runtime-decompiler/src/main/java/org/jrd/frontend/utility/ScreenFinder.java
> WIP: Fixing issues

- runtime-decompiler/pom.xml
CPLC 2.0 has just been released.
It should have fixed many small issues.
> Update CPLC dependency

- start.bat
Some code was me in 2019 copying https://github.com/AdoptOpenJDK/IcedTea-Web/commits/master/launchers/shell-launcher/launchers.bat.in, tried to explain it.
https://ss64.com/nt/ is a good source of CMD command knowledge.
> Verbosely commented batch launch script

- runtime-decompiler/src/main/java/org/jrd/backend/core/DecompilerRequestReceiver.java
- runtime-decompiler/src/main/java/org/jrd/backend/core/Logger.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/DecompilerWrapper.java
- runtime-decompiler/src/main/java/org/jrd/backend/decompiling/PluginManager.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/plugins/OkCancelPanel.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/plugins/PluginConfigurationEditorController.java
- runtime-decompiler/src/main/java/org/jrd/frontend/frame/plugins/PluginConfigurationEditorView.java
- runtime-decompiler/src/plugins/CfrDecompilerWrapper.java
- runtime-decompiler/src/plugins/FernflowerDecompilerWrapper.java
https://github.com/pmikova/java-runtime-decompiler/issues/238
todo: make it optional
todo: make optional init on all
todo: revisit procyon to accept more classes
> WIP include (optionally) all classes for decompilers
